# Generated by Django 2.1 on 2018-08-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.Membership'),
        ),
    ]
