# Generated by Django 2.1 on 2018-08-23 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20160107_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_excl_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_from', models.DateTimeField()),
                ('valid_til', models.DateTimeField()),
                ('stockrecord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_price', to='partner.StockRecord')),
            ],
        ),
    ]
