# Generated by Django 2.1 on 2018-08-24 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_saleprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleprice',
            name='stockrecord',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partner.StockRecord'),
        ),
    ]
